language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install numpy 
  - pip install matplotlib
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=bioalgo
after_success:
  - coveralls